import { PrismaClient } from "@prisma/client";
import { Request, Response, Router } from "express";
const db = new PrismaClient();

async function main(req: Request, res: Response) {
    await db.student.createMany({
        data: [
            {
                name: "John Doe",
                gender: "Male",
                fatherName: "Michael Doe",
                motherName: "Sarah Doe",
                whattsapNumber: "1234567890",
                callNumber: "0987654321",
                motherNumber: "1234509876",
                fatherNumber: "0987612345",
                language: "English",
                target: "Engineering",
                StudyHours: 6,
                class: "12th",
                dropperStatus: "No",
                previousScore: "90%",
                platform: "Online",
                expectation: "To excel in JEE",
                groupMentorId: "876642ae-581a-4492-8995-c618a2940c06",
            },
            {
                name: "Jane Smith",
                gender: "Female",
                fatherName: "Robert Smith",
                motherName: "Emily Smith",
                whattsapNumber: "1231231231",
                callNumber: "3213213210",
                motherNumber: "4564564567",
                fatherNumber: "6546546543",
                language: "Hindi",
                target: "Medical",
                StudyHours: 8,
                class: "12th",
                dropperStatus: "Yes",
                previousScore: "85%",
                platform: "Offline",
                expectation: "To crack NEET",
                groupMentorId: "876642ae-581a-4492-8995-c618a2940c06",
            },
            {
                name: "Alice Johnson",
                gender: "Female",
                fatherName: "Paul Johnson",
                motherName: "Anna Johnson",
                whattsapNumber: "5555555555",
                callNumber: "5555551234",
                motherNumber: "5555554321",
                fatherNumber: "5555559876",
                language: "English",
                target: "Commerce",
                StudyHours: 5,
                class: "11th",
                dropperStatus: "No",
                previousScore: "80%",
                platform: "Hybrid",
                expectation: "To excel in board exams",
                groupMentorId: "876642ae-581a-4492-8995-c618a2940c06",
            },
            {
                name: "David Brown",
                gender: "Male",
                fatherName: "George Brown",
                motherName: "Laura Brown",
                whattsapNumber: "9876543210",
                callNumber: "8765432109",
                motherNumber: "1234567899",
                fatherNumber: "9876541234",
                language: "English",
                target: "Engineering",
                StudyHours: 7,
                class: "12th",
                dropperStatus: "Yes",
                previousScore: "88%",
                platform: "Online",
                expectation: "To get into top IIT",
                groupMentorId: "876642ae-581a-4492-8995-c618a2940c06",
            },
            {
                name: "Olivia Wilson",
                gender: "Female",
                fatherName: "Henry Wilson",
                motherName: "Nancy Wilson",
                whattsapNumber: "6666666666",
                callNumber: "1234123412",
                motherNumber: "0987098709",
                fatherNumber: "1122112211",
                language: "Hindi",
                target: "Arts",
                StudyHours: 4,
                class: "11th",
                dropperStatus: "No",
                previousScore: "75%",
                platform: "Offline",
                expectation: "To focus on UPSC preparation",
                groupMentorId: "876642ae-581a-4492-8995-c618a2940c06",
            },
        ],
    });
    res.status(200).send("Data inserted successfully");
}

const router = Router();
router.get("/", main);
export default router;