import { PrismaClient } from "@prisma/client";
import { Request, Response, Router } from "express";
const db = new PrismaClient();

async function main(req: Request, res: Response) {
    await db.student.createMany({
        data: [
            {
                name: "Kushal Goyal",
                gender: "Male",
                fatherName: "Michael Doe",
                motherName: "Sarah Doe",
                whattsapNumber: "1234567895",
                callNumber: "8307846578",
                motherNumber: "1234509876",
                fatherNumber: "0987612345",
                language: "English",
                target: "Engineering",
                StudyHours: 6,
                class: "12th",
                dropperStatus: "No",
                previousScore: "90%",
                platform: "Online",
                expectation: "To excel in JEE",
            },
            {
                name: "Prabhjot Kaur",
                gender: "Female",
                fatherName: "Robert Smith",
                motherName: "Emily Smith",
                whattsapNumber: "1234567897",
                callNumber: "3213213210",
                motherNumber: "4564564567",
                fatherNumber: "6546546543",
                language: "Hindi",
                target: "Medical",
                StudyHours: 8,
                class: "12th",
                dropperStatus: "Yes",
                previousScore: "85%",
                platform: "Offline",
                expectation: "To crack NEET",
            },
            {
                name: "Ansh Gupta",
                gender: "Female",
                fatherName: "Paul Johnson",
                motherName: "Anna Johnson",
                whattsapNumber: "1234567891",
                callNumber: "5555551234",
                motherNumber: "5555554321",
                fatherNumber: "5555559876",
                language: "English",
                target: "Commerce",
                StudyHours: 5,
                class: "11th",
                dropperStatus: "No",
                previousScore: "80%",
                platform: "Hybrid",
                expectation: "To excel in board exams",
            },
            {
                name: "Krishna Singh",
                gender: "Male",
                fatherName: "George Brown",
                motherName: "Laura Brown",
                whattsapNumber: "1234567898",
                callNumber: "8765432109",
                motherNumber: "1234567899",
                fatherNumber: "9876541234",
                language: "English",
                target: "Engineering",
                StudyHours: 7,
                class: "12th",
                dropperStatus: "Yes",
                previousScore: "88%",
                platform: "Online",
                expectation: "To get into top IIT",
            },
            {
                name: "Yashika Sharma",
                gender: "Female",
                fatherName: "Henry Wilson",
                motherName: "Nancy Wilson",
                whattsapNumber: "1234567899",
                callNumber: "1234123412",
                motherNumber: "0987098709",
                fatherNumber: "1122112211",
                language: "Hindi",
                target: "Arts",
                StudyHours: 4,
                class: "11th",
                dropperStatus: "No",
                previousScore: "75%",
                platform: "Offline",
                expectation: "To focus on UPSC preparation",
            },
        ],
    });
    res.status(200).send("Data inserted successfully");
}

const router = Router();
router.get("/", main);
export default router;
